#!/usr/bin/env python3
"""Generate the FDK-exact Q15 DCT-IV pre/post rotation ROM.

The generator parses only authoritative hexadecimal literals from
libFDK/src/FDK_tools_rom.cpp.  It deliberately does not use math.sin/cos or
host floating point, because the selected FDK Q31-to-Q15 conversion and table
indexing are part of the bit-exact contract.

Run from the repository root:
  python3 my_workspace/window_mdct/tools/gen_mdct_rotation_rom.py
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def signed32(value: int) -> int:
    """Interpret an eight-digit hexadecimal literal as signed 32 bit."""
    return value - (1 << 32) if value & 0x8000_0000 else value


def fdk_q31_literal_to_q15(hex_text: str) -> int:
    """Mirror FX_DBL2FXCONST_SGL from libFDK/include/common_fix.h."""
    value = signed32(int(hex_text, 16))
    shifted_once = (value >> 15) + 1
    if value > 0 and shifted_once > 0xFFFF:
        return 0x7FFF
    result = shifted_once >> 1
    if not -(1 << 15) <= result < (1 << 15):
        raise ValueError(f"Q15 conversion overflow for 0x{hex_text}: {result}")
    return result


def extract_pairs(
    source: str,
    c_type: str,
    table_name: str,
    macro_name: str,
    expected_count: int,
) -> list[tuple[int, int]]:
    """Extract one packed FDK coefficient array and convert it to Q15."""
    match = re.search(
        rf"const\s+{re.escape(c_type)}\s+{re.escape(table_name)}\[\]\s*=\s*"
        rf"\{{(.*?)\n\}};",
        source,
        flags=re.DOTALL,
    )
    if match is None:
        raise ValueError(f"cannot find {table_name} in FDK_tools_rom.cpp")

    literals = re.findall(
        rf"{re.escape(macro_name)}\(0x([0-9A-Fa-f]{{8}}),\s*"
        rf"0x([0-9A-Fa-f]{{8}})\)",
        match.group(1),
    )
    if len(literals) != expected_count:
        raise ValueError(
            f"{table_name}: got {len(literals)} entries, "
            f"expected {expected_count}"
        )
    return [
        (fdk_q31_literal_to_q15(cos_hex), fdk_q31_literal_to_q15(sin_hex))
        for cos_hex, sin_hex in literals
    ]


def q15_hex(value: int) -> str:
    return f"{value & 0xFFFF:04X}"


def format_rom(name: str, rom_type: str, values: list[tuple[int, int]]) -> str:
    rows: list[str] = []
    for index, (cos_value, sin_value) in enumerate(values):
        comma = "," if index + 1 < len(values) else ""
        rows.append(
            f'    {index:3d} => (cos_q15 => signed\'(x"{q15_hex(cos_value)}"), '
            f'sin_q15 => signed\'(x"{q15_hex(sin_value)}")){comma}'
        )
    return f"  constant {name} : {rom_type} := (\n" + "\n".join(rows) + "\n  );\n"


def render_vhdl(
    pre_long: list[tuple[int, int]],
    pre_short: list[tuple[int, int]],
    post: list[tuple[int, int]],
    source_path: str,
) -> str:
    constants = "\n".join(
        (
            format_rom("PRE_LONG_ROM", "pre_long_rom_t", pre_long),
            format_rom("PRE_SHORT_ROM", "pre_short_rom_t", pre_short),
            format_rom("POST_ROM", "post_rom_t", post),
        )
    )
    return f'''-------------------------------------------------------------------------------
-- AUTO-GENERATED by tools/gen_mdct_rotation_rom.py; do not edit literals.
-- Source: {source_path}
-- Conversion: FX_DBL2FXCONST_SGL (FDK Q31 literal -> selected Q15 profile).
--
-- PRE L=1024 : SineWindow1024
-- PRE L=128  : SineWindow128
-- POST       : SineTable1024[2*i], compacted for the long stride.
-- Short POST addresses POST_ROM[8*i], hence physical SineTable stride 16.
-------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mdct_rotation_rom is
  generic (
    -- 0: DCT-IV pre rotation; 1: DCT-IV post rotation.
    ROM_KIND : natural := 0
  );
  port (
    -- 0: L=128; 1: L=1024.
    size_mode : in  std_logic;
    -- PRE: packed FFT index selector t (0..63/511).
    -- POST: rotation number i (0..31/255).
    rot_index : in  unsigned(8 downto 0);
    cos_q15   : out signed(15 downto 0);
    sin_q15   : out signed(15 downto 0)
  );
end entity mdct_rotation_rom;

architecture rtl of mdct_rotation_rom is
  constant KIND_PRE  : natural := 0;
  constant KIND_POST : natural := 1;
  type coeff_pair_t is record
    cos_q15 : signed(15 downto 0);
    sin_q15 : signed(15 downto 0);
  end record;
  type pre_long_rom_t  is array (0 to 511) of coeff_pair_t;
  type pre_short_rom_t is array (0 to 63) of coeff_pair_t;
  type post_rom_t      is array (0 to 255) of coeff_pair_t;

{constants}
begin
  assert ROM_KIND = KIND_PRE or ROM_KIND = KIND_POST
    report "mdct_rotation_rom: ROM_KIND must be 0 (PRE) or 1 (POST)"
    severity failure;

  process(all)
    variable index_value : natural range 0 to 511;
    variable post_addr   : natural range 0 to 255;
  begin
    cos_q15 <= signed'(x"7FFF");
    sin_q15 <= signed'(x"0000");
    index_value := 0;
    post_addr := 0;

    if not is_x(std_logic_vector(rot_index)) then
      index_value := to_integer(rot_index);
      if ROM_KIND = KIND_PRE then
        if size_mode = '1' then
          assert index_value <= 511
            report "mdct_rotation_rom: long PRE index outside 0..511"
            severity error;
          if index_value <= 511 then
            cos_q15 <= PRE_LONG_ROM(index_value).cos_q15;
            sin_q15 <= PRE_LONG_ROM(index_value).sin_q15;
          end if;
        elsif size_mode = '0' then
          assert index_value <= 63
            report "mdct_rotation_rom: short PRE index outside 0..63"
            severity error;
          if index_value <= 63 then
            cos_q15 <= PRE_SHORT_ROM(index_value).cos_q15;
            sin_q15 <= PRE_SHORT_ROM(index_value).sin_q15;
          end if;
        end if;
      else
        if size_mode = '1' then
          assert index_value <= 255
            report "mdct_rotation_rom: long POST index outside 0..255"
            severity error;
          if index_value <= 255 then post_addr := index_value; end if;
        elsif size_mode = '0' then
          assert index_value <= 31
            report "mdct_rotation_rom: short POST index outside 0..31"
            severity error;
          if index_value <= 31 then post_addr := index_value * 8; end if;
        end if;
        cos_q15 <= POST_ROM(post_addr).cos_q15;
        sin_q15 <= POST_ROM(post_addr).sin_q15;
      end if;
    end if;
  end process;
end architecture rtl;
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("libFDK/src/FDK_tools_rom.cpp"),
        help="FDK ROM source, relative to the repository root",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("my_workspace/window_mdct/rtl/mdct_rotation_rom.vhd"),
        help="generated VHDL output",
    )
    args = parser.parse_args()

    source = args.source.read_text(encoding="utf-8")
    pre_long = extract_pairs(source, "FIXP_WTP", "SineWindow1024", "WTCP", 512)
    pre_short = extract_pairs(source, "FIXP_WTP", "SineWindow128", "WTCP", 64)
    sine_table = extract_pairs(source, "FIXP_STP", "SineTable1024", "STCP", 513)
    post = [sine_table[2 * index] for index in range(256)]

    output = render_vhdl(pre_long, pre_short, post, args.source.as_posix())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output, encoding="utf-8", newline="\n")
    print(
        f"wrote {args.out} "
        f"({len(pre_long) + len(pre_short) + len(post)} Q15 pairs)"
    )


if __name__ == "__main__":
    main()

