#!/usr/bin/env python3
"""Generate the synthesizable Q15 MDCT analysis-window ROM from FDK-AAC.

The checked-in VHDL is generated from the authoritative WTCP literals in
libFDK/src/FDK_tools_rom.cpp.  Golden coefficients are never recomputed with
sin(), Bessel functions, or host floating point.

Usage (from the repository root):
  python my_workspace/window_mdct/tools/gen_mdct_window_rom.py
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


TABLES = (
    ("SineWindow1024", 512, "SINE_LONG"),
    ("KBDWindow1024", 512, "KBD_LONG"),
    ("SineWindow128", 64, "SINE_SHORT"),
    ("KBDWindow128", 64, "KBD_SHORT"),
)


def signed32(value: int) -> int:
    return value - (1 << 32) if value & 0x8000_0000 else value


def fdk_q31_literal_to_q15(hex_text: str) -> int:
    """Mirror FX_DBL2FXCONST_SGL from libFDK/include/common_fix.h."""
    value = signed32(int(hex_text, 16))
    shifted_once = (value >> 15) + 1
    if value > 0 and shifted_once > 0xFFFF:
        return 0x7FFF
    result = shifted_once >> 1
    if not -(1 << 15) <= result < (1 << 15):
        raise ValueError(f"Q15 conversion overflow for 0x{hex_text}: {result}")
    return result


def extract_table(source: str, name: str, expected: int) -> list[tuple[int, int]]:
    match = re.search(
        rf"const\s+FIXP_WTP\s+{re.escape(name)}\[\]\s*=\s*\{{(.*?)\n\}};",
        source,
        flags=re.DOTALL,
    )
    if match is None:
        raise ValueError(f"cannot find {name} in FDK_tools_rom.cpp")
    literals = re.findall(
        r"WTCP\(0x([0-9A-Fa-f]{8}),\s*0x([0-9A-Fa-f]{8})\)",
        match.group(1),
    )
    if len(literals) != expected:
        raise ValueError(f"{name}: got {len(literals)} entries, expected {expected}")
    return [
        (fdk_q31_literal_to_q15(re_hex), fdk_q31_literal_to_q15(im_hex))
        for re_hex, im_hex in literals
    ]


def q15_hex(value: int) -> str:
    return f"{value & 0xFFFF:04X}"


def format_rom(name: str, values: list[tuple[int, int]], rom_type: str) -> str:
    rows = []
    for index, (re_value, im_value) in enumerate(values):
        comma = "," if index != len(values) - 1 else ""
        rows.append(
            f'    {index:3d} => (signed\'(x"{q15_hex(re_value)}"), '
            f'signed\'(x"{q15_hex(im_value)}")){comma}'
        )
    return f"  constant {name} : {rom_type} := (\n" + "\n".join(rows) + "\n  );\n"


def render_vhdl(tables: dict[str, list[tuple[int, int]]], source_rel: str) -> str:
    constants = []
    for _, expected, vhdl_name in TABLES:
        rom_type = "window_long_rom_t" if expected == 512 else "window_short_rom_t"
        constants.append(format_rom(vhdl_name, tables[vhdl_name], rom_type))
    return f'''-------------------------------------------------------------------------------
-- AUTO-GENERATED by tools/gen_mdct_window_rom.py; do not edit literals.
-- Source: {source_rel}
-- Conversion: FX_DBL2FXCONST_SGL (FDK Q31 literal -> selected Q15 profile).
--
-- One registered read port is sufficient because each folded output uses at
-- most one slope entry.  The PCM memory is read in the same issue cycle, so
-- coefficient and PCM data remain naturally aligned.
-------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.mdct_pkg.all;

entity mdct_window_rom is
  port (
    clk       : in  std_logic;
    en        : in  std_logic;
    size_mode : in  std_logic; -- 0=slope128, 1=slope1024
    shape     : in  mdct_shape_t;
    addr      : in  unsigned(8 downto 0);
    valid     : out std_logic;
    coeff_re  : out mdct_coeff_t;
    coeff_im  : out mdct_coeff_t
  );
end entity mdct_window_rom;

architecture rtl of mdct_window_rom is
  type window_entry_t is record
    re_value : mdct_coeff_t;
    im_value : mdct_coeff_t;
  end record;
  type window_long_rom_t  is array (0 to 511) of window_entry_t;
  type window_short_rom_t is array (0 to 63) of window_entry_t;

{''.join(constants)}
begin
  process(clk)
    variable index_v : natural;
  begin
    if rising_edge(clk) then
      valid <= en;
      if en = '1' then
        index_v := to_integer(addr);
        if size_mode = MDCT_FFT512 then
          assert index_v < 512
            report "mdct_window_rom: long address outside 0..511"
            severity failure;
          if shape = MDCT_KBD then
            coeff_re <= KBD_LONG(index_v).re_value;
            coeff_im <= KBD_LONG(index_v).im_value;
          else
            coeff_re <= SINE_LONG(index_v).re_value;
            coeff_im <= SINE_LONG(index_v).im_value;
          end if;
        else
          assert index_v < 64
            report "mdct_window_rom: short address outside 0..63"
            severity failure;
          if shape = MDCT_KBD then
            coeff_re <= KBD_SHORT(index_v).re_value;
            coeff_im <= KBD_SHORT(index_v).im_value;
          else
            coeff_re <= SINE_SHORT(index_v).re_value;
            coeff_im <= SINE_SHORT(index_v).im_value;
          end if;
        end if;
      end if;
    end if;
  end process;
end architecture rtl;
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("libFDK/src/FDK_tools_rom.cpp"),
        help="FDK ROM source, relative to the repository root",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("my_workspace/window_mdct/rtl/mdct_window_rom.vhd"),
        help="generated VHDL output",
    )
    args = parser.parse_args()

    source = args.source.read_text(encoding="utf-8")
    tables: dict[str, list[tuple[int, int]]] = {}
    for fdk_name, expected, vhdl_name in TABLES:
        tables[vhdl_name] = extract_table(source, fdk_name, expected)

    output = render_vhdl(tables, args.source.as_posix())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output, encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({sum(len(v) for v in tables.values())} Q15 pairs)")


if __name__ == "__main__":
    main()
