-------------------------------------------------------------------------------
-- AUTO-GENERATED by tools/gen_fdk_twiddle.py.  Do not edit by hand.
-- Source : libFDK/src/FDK_tools_rom.cpp, SineTable512
-- Profile: FDK_AACLC_1024_Q31Q15_RAD2_V1
-- Q15 octant SHA-256: 95eb626e5d5a6f44fdbd00f5700bb5f8b1b8e9425d20d374412968090d595ad9
--
-- Input phase_index k denotes W512(k) = exp(-j*2*pi*k/512), k=0..255.
-- Only 65 positive-magnitude points over 0..pi/4 are stored.  The combinational
-- folding below reconstructs |cos|, |sin| and the sign of cos.  sin is
-- non-negative over the required half-circle.  The butterfly applies signs
-- after each Q31xQ15 product has been truncated, matching FDK arithmetic.
-------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity fft_radix2_twiddle_rom is
  port (
    phase_index : in  unsigned(7 downto 0);
    cos_mag     : out signed(15 downto 0);
    sin_mag     : out signed(15 downto 0);
    cos_neg     : out std_logic
  );
end entity fft_radix2_twiddle_rom;

architecture rtl of fft_radix2_twiddle_rom is
  type pair_t is record
    cos_q15 : signed(15 downto 0);
    sin_q15 : signed(15 downto 0);
  end record;
  type octant_t is array (0 to 64) of pair_t;

  constant OCTANT : octant_t := (
     0 => (cos_q15 => signed'(x"7FFF"), sin_q15 => signed'(x"0000")),
     1 => (cos_q15 => signed'(x"7FFE"), sin_q15 => signed'(x"0192")),
     2 => (cos_q15 => signed'(x"7FF6"), sin_q15 => signed'(x"0324")),
     3 => (cos_q15 => signed'(x"7FEA"), sin_q15 => signed'(x"04B6")),
     4 => (cos_q15 => signed'(x"7FD9"), sin_q15 => signed'(x"0648")),
     5 => (cos_q15 => signed'(x"7FC2"), sin_q15 => signed'(x"07D9")),
     6 => (cos_q15 => signed'(x"7FA7"), sin_q15 => signed'(x"096B")),
     7 => (cos_q15 => signed'(x"7F87"), sin_q15 => signed'(x"0AFB")),
     8 => (cos_q15 => signed'(x"7F62"), sin_q15 => signed'(x"0C8C")),
     9 => (cos_q15 => signed'(x"7F38"), sin_q15 => signed'(x"0E1C")),
    10 => (cos_q15 => signed'(x"7F0A"), sin_q15 => signed'(x"0FAB")),
    11 => (cos_q15 => signed'(x"7ED6"), sin_q15 => signed'(x"113A")),
    12 => (cos_q15 => signed'(x"7E9D"), sin_q15 => signed'(x"12C8")),
    13 => (cos_q15 => signed'(x"7E60"), sin_q15 => signed'(x"1455")),
    14 => (cos_q15 => signed'(x"7E1E"), sin_q15 => signed'(x"15E2")),
    15 => (cos_q15 => signed'(x"7DD6"), sin_q15 => signed'(x"176E")),
    16 => (cos_q15 => signed'(x"7D8A"), sin_q15 => signed'(x"18F9")),
    17 => (cos_q15 => signed'(x"7D3A"), sin_q15 => signed'(x"1A83")),
    18 => (cos_q15 => signed'(x"7CE4"), sin_q15 => signed'(x"1C0C")),
    19 => (cos_q15 => signed'(x"7C89"), sin_q15 => signed'(x"1D93")),
    20 => (cos_q15 => signed'(x"7C2A"), sin_q15 => signed'(x"1F1A")),
    21 => (cos_q15 => signed'(x"7BC6"), sin_q15 => signed'(x"209F")),
    22 => (cos_q15 => signed'(x"7B5D"), sin_q15 => signed'(x"2224")),
    23 => (cos_q15 => signed'(x"7AEF"), sin_q15 => signed'(x"23A7")),
    24 => (cos_q15 => signed'(x"7A7D"), sin_q15 => signed'(x"2528")),
    25 => (cos_q15 => signed'(x"7A06"), sin_q15 => signed'(x"26A8")),
    26 => (cos_q15 => signed'(x"798A"), sin_q15 => signed'(x"2827")),
    27 => (cos_q15 => signed'(x"790A"), sin_q15 => signed'(x"29A4")),
    28 => (cos_q15 => signed'(x"7885"), sin_q15 => signed'(x"2B1F")),
    29 => (cos_q15 => signed'(x"77FB"), sin_q15 => signed'(x"2C99")),
    30 => (cos_q15 => signed'(x"776C"), sin_q15 => signed'(x"2E11")),
    31 => (cos_q15 => signed'(x"76D9"), sin_q15 => signed'(x"2F87")),
    32 => (cos_q15 => signed'(x"7642"), sin_q15 => signed'(x"30FC")),
    33 => (cos_q15 => signed'(x"75A6"), sin_q15 => signed'(x"326E")),
    34 => (cos_q15 => signed'(x"7505"), sin_q15 => signed'(x"33DF")),
    35 => (cos_q15 => signed'(x"7460"), sin_q15 => signed'(x"354E")),
    36 => (cos_q15 => signed'(x"73B6"), sin_q15 => signed'(x"36BA")),
    37 => (cos_q15 => signed'(x"7308"), sin_q15 => signed'(x"3825")),
    38 => (cos_q15 => signed'(x"7255"), sin_q15 => signed'(x"398D")),
    39 => (cos_q15 => signed'(x"719E"), sin_q15 => signed'(x"3AF3")),
    40 => (cos_q15 => signed'(x"70E3"), sin_q15 => signed'(x"3C57")),
    41 => (cos_q15 => signed'(x"7023"), sin_q15 => signed'(x"3DB8")),
    42 => (cos_q15 => signed'(x"6F5F"), sin_q15 => signed'(x"3F17")),
    43 => (cos_q15 => signed'(x"6E97"), sin_q15 => signed'(x"4074")),
    44 => (cos_q15 => signed'(x"6DCA"), sin_q15 => signed'(x"41CE")),
    45 => (cos_q15 => signed'(x"6CF9"), sin_q15 => signed'(x"4326")),
    46 => (cos_q15 => signed'(x"6C24"), sin_q15 => signed'(x"447B")),
    47 => (cos_q15 => signed'(x"6B4B"), sin_q15 => signed'(x"45CD")),
    48 => (cos_q15 => signed'(x"6A6E"), sin_q15 => signed'(x"471D")),
    49 => (cos_q15 => signed'(x"698C"), sin_q15 => signed'(x"486A")),
    50 => (cos_q15 => signed'(x"68A7"), sin_q15 => signed'(x"49B4")),
    51 => (cos_q15 => signed'(x"67BD"), sin_q15 => signed'(x"4AFB")),
    52 => (cos_q15 => signed'(x"66D0"), sin_q15 => signed'(x"4C40")),
    53 => (cos_q15 => signed'(x"65DE"), sin_q15 => signed'(x"4D81")),
    54 => (cos_q15 => signed'(x"64E9"), sin_q15 => signed'(x"4EC0")),
    55 => (cos_q15 => signed'(x"63EF"), sin_q15 => signed'(x"4FFB")),
    56 => (cos_q15 => signed'(x"62F2"), sin_q15 => signed'(x"5134")),
    57 => (cos_q15 => signed'(x"61F1"), sin_q15 => signed'(x"5269")),
    58 => (cos_q15 => signed'(x"60EC"), sin_q15 => signed'(x"539B")),
    59 => (cos_q15 => signed'(x"5FE4"), sin_q15 => signed'(x"54CA")),
    60 => (cos_q15 => signed'(x"5ED7"), sin_q15 => signed'(x"55F6")),
    61 => (cos_q15 => signed'(x"5DC8"), sin_q15 => signed'(x"571E")),
    62 => (cos_q15 => signed'(x"5CB4"), sin_q15 => signed'(x"5843")),
    63 => (cos_q15 => signed'(x"5B9D"), sin_q15 => signed'(x"5964")),
    64 => (cos_q15 => signed'(x"5A82"), sin_q15 => signed'(x"5A82"))
  );
begin
  process(all)
    variable k, base : natural range 0 to 255;
    variable swap_cs : boolean;
  begin
    -- During time-zero delta cycles the upstream address generator may not
    -- have driven this resolved port yet.  Select W=1 until all bits are
    -- known; normal operation always supplies a binary value in 0..255.
    if is_x(std_logic_vector(phase_index)) then
      k := 0;
    else
      k := to_integer(phase_index);
    end if;

    -- Fold 0..pi into the first octant.  phase_index never exceeds 255 in the
    -- FFT, therefore sin(theta) is always non-negative.
    if k <= 64 then
      base := k;
      swap_cs := false;
      cos_neg <= '0';
    elsif k <= 128 then
      base := 128 - k;
      swap_cs := true;
      cos_neg <= '0';
    elsif k <= 192 then
      base := k - 128;
      swap_cs := true;
      cos_neg <= '1';
    else
      base := 256 - k;
      swap_cs := false;
      cos_neg <= '1';
    end if;

    if swap_cs then
      cos_mag <= OCTANT(base).sin_q15;
      sin_mag <= OCTANT(base).cos_q15;
    else
      cos_mag <= OCTANT(base).cos_q15;
      sin_mag <= OCTANT(base).sin_q15;
    end if;
  end process;
end architecture rtl;
