#!/usr/bin/env python3
"""Generate the FFT twiddle sources from the authoritative FDK table.

The production profile uses the x86/x64 FDK configuration where ``STC``
converts the Q1.31 literals in ``SineTable512`` to Q1.15 with rounding.  A
radix-2 FFT-512 only needs 65 points in the first octant; the RTL reconstructs
the remaining signs and swaps from the logical phase index 0..255.

Generated files:

* ``rtl/fft_radix2_twiddle_rom.vhd``
* ``ref/fdk_sinetable512_q15.h``
* ``ref/fdk_sinetable512_q15.py``

Run this script from any directory.  It never evaluates sin/cos, so its output
stays tied to the checked-out FDK source rather than the host math library.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path


CORE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = CORE_ROOT.parents[2]
FDK_ROM = REPO_ROOT / "libFDK" / "src" / "FDK_tools_rom.cpp"


def q31_literal_to_q15(raw_hex: str) -> int:
    """Mirror FX_DBL2FXCONST_SGL for the non-negative sine-table literals."""

    raw = int(raw_hex, 16)
    rounded = ((raw >> 15) + 1) >> 1
    return min(0x7FFF, rounded)


def extract_octant() -> list[tuple[int, int]]:
    source = FDK_ROM.read_text(encoding="utf-8")
    marker = "const FIXP_STP SineTable512[]"
    start = source.index(marker)
    body = source[start : source.index("};", start)]
    pairs = re.findall(
        r"STCP\(0x([0-9a-fA-F]{8}),\s*0x([0-9a-fA-F]{8})\)", body
    )
    if len(pairs) != 257:
        raise RuntimeError(f"expected 257 SineTable512 entries, found {len(pairs)}")

    # The table spans 0..pi/4 in 256 intervals.  FFT phase indices land on
    # every fourth entry, producing exactly 65 points including both ends.
    octant = [
        (q31_literal_to_q15(pairs[4 * i][0]), q31_literal_to_q15(pairs[4 * i][1]))
        for i in range(65)
    ]
    if octant[0] != (0x7FFF, 0x0000) or octant[-1] != (0x5A82, 0x5A82):
        raise RuntimeError("unexpected SineTable512 endpoints after Q15 conversion")
    return octant


def fingerprint(values: list[tuple[int, int]]) -> str:
    packed = b"".join(
        cos_q15.to_bytes(2, "big") + sin_q15.to_bytes(2, "big")
        for cos_q15, sin_q15 in values
    )
    return hashlib.sha256(packed).hexdigest()


def render_vhdl(values: list[tuple[int, int]], sha256: str) -> str:
    rows = ",\n".join(
        f'    {i:2d} => (cos_q15 => signed\'(x"{c:04X}"), '
        f'sin_q15 => signed\'(x"{s:04X}"))'
        for i, (c, s) in enumerate(values)
    )
    return f"""-------------------------------------------------------------------------------
-- AUTO-GENERATED by tools/gen_fdk_twiddle.py.  Do not edit by hand.
-- Source : libFDK/src/FDK_tools_rom.cpp, SineTable512
-- Profile: FDK_AACLC_1024_Q31Q15_RAD2_V1
-- Q15 octant SHA-256: {sha256}
--
-- Input phase_index k denotes W512(k) = exp(-j*2*pi*k/512), k=0..255.
-- Only 65 positive-magnitude points over 0..pi/4 are stored.  The combinational
-- folding below reconstructs |cos|, |sin| and the sign of cos.  sin is
-- non-negative over the required half-circle.  The butterfly applies signs
-- after each Q31xQ15 product has been truncated, matching FDK arithmetic.
-------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity fft_radix2_twiddle_rom is
  port (
    phase_index : in  unsigned(7 downto 0);
    cos_mag     : out signed(15 downto 0);
    sin_mag     : out signed(15 downto 0);
    cos_neg     : out std_logic
  );
end entity fft_radix2_twiddle_rom;

architecture rtl of fft_radix2_twiddle_rom is
  type pair_t is record
    cos_q15 : signed(15 downto 0);
    sin_q15 : signed(15 downto 0);
  end record;
  type octant_t is array (0 to 64) of pair_t;

  constant OCTANT : octant_t := (
{rows}
  );
begin
  process(all)
    variable k, base : natural range 0 to 255;
    variable swap_cs : boolean;
  begin
    -- During time-zero delta cycles the upstream address generator may not
    -- have driven this resolved port yet.  Select W=1 until all bits are
    -- known; normal operation always supplies a binary value in 0..255.
    if is_x(std_logic_vector(phase_index)) then
      k := 0;
    else
      k := to_integer(phase_index);
    end if;

    -- Fold 0..pi into the first octant.  phase_index never exceeds 255 in the
    -- FFT, therefore sin(theta) is always non-negative.
    if k <= 64 then
      base := k;
      swap_cs := false;
      cos_neg <= '0';
    elsif k <= 128 then
      base := 128 - k;
      swap_cs := true;
      cos_neg <= '0';
    elsif k <= 192 then
      base := k - 128;
      swap_cs := true;
      cos_neg <= '1';
    else
      base := 256 - k;
      swap_cs := false;
      cos_neg <= '1';
    end if;

    if swap_cs then
      cos_mag <= OCTANT(base).sin_q15;
      sin_mag <= OCTANT(base).cos_q15;
    else
      cos_mag <= OCTANT(base).cos_q15;
      sin_mag <= OCTANT(base).sin_q15;
    end if;
  end process;
end architecture rtl;
"""


def render_cpp(values: list[tuple[int, int]], sha256: str) -> str:
    rows = ",\n".join(f"    {{0x{c:04X}, 0x{s:04X}}}" for c, s in values)
    return f"""// AUTO-GENERATED by tools/gen_fdk_twiddle.py.  Do not edit.
// Q15 octant SHA-256: {sha256}
#ifndef FDK_SINETABLE512_Q15_H
#define FDK_SINETABLE512_Q15_H

#include <array>
#include <cstdint>

struct FdkTwiddleQ15 {{
  int16_t cos_q15;
  int16_t sin_q15;
}};

inline constexpr std::array<FdkTwiddleQ15, 65> kFdkSineTable512Octant = {{{{
{rows}
}}}};

inline constexpr const char *kFdkSineTable512OctantSha256 =
    "{sha256}";

#endif
"""


def render_python(values: list[tuple[int, int]], sha256: str) -> str:
    rows = ",\n".join(f"    (0x{c:04X}, 0x{s:04X})" for c, s in values)
    return f'''"""AUTO-GENERATED FDK SineTable512 first-octant values in Q1.15."""

OCTANT_SHA256 = "{sha256}"
OCTANT_Q15 = (
{rows},
)
'''


def write_if_changed(path: Path, text: str) -> None:
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        print(f"unchanged: {path.relative_to(REPO_ROOT)}")
        return
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote:     {path.relative_to(REPO_ROOT)}")


def main() -> None:
    values = extract_octant()
    sha256 = fingerprint(values)
    write_if_changed(
        CORE_ROOT / "rtl" / "fft_radix2_twiddle_rom.vhd",
        render_vhdl(values, sha256),
    )
    write_if_changed(
        CORE_ROOT / "ref" / "fdk_sinetable512_q15.h",
        render_cpp(values, sha256),
    )
    write_if_changed(
        CORE_ROOT / "ref" / "fdk_sinetable512_q15.py",
        render_python(values, sha256),
    )


if __name__ == "__main__":
    main()
